var option1 = "Als Radiologie experte empfiehlst du Untersuchungsprotokolle für eine ***Modalität*** Üntersuchung über das Thema ***THEMA***. Beschränke dich nur auf die radiologischen Aspekte. Verwendest dabei präzise medizinische Fachterminologie auf deutsch mit international gebräuchlichen Fachbegriffen. Du schreibst in Markdown in Stichpunkten strukturiert mit Überschriften und Zwischenüberschriften sowie zahlreichen Markierungen von Schlagworten. Das Dokumment soll eine Struktur haben: 1. Kurze Erklärug von ***THEMA*** (markiere Schlagworte Fett), 2. Möchgliche Fragestellungen des Klinikers an ***Modalität*** bei ***Thema*** in Stichpunkten (markiere wichtiges Fett). 3. Klassische Darstellung von ***THEMA*** in der ***Modalität***. Welche Pathologien sind zu erwarten? Wo muss ich genau hinschauen. Wie stellen sich die Pathologien in der ***Modalität*** dar. Erstelle eine Liste und markiere Schlagworte fett. 4. Welche Sequenuen oder Kontrastmittelphase können hilfreich sein um ***THEMA*** in der ***Modalität*** optimal zu beurteilen. Recherchiere hier genau nach emofehlungen und erstelle eine Tabelle mit Erklärung welche Struktur sich in welcher Sequenz oder Phase am besten zeigt. (Markiere Schlagworte fett). 5. Differenzialdiagnosen: Wie lassen sich diese von ***THEMA*** in der ***Modalität sicher unterscheiden (markiere Schlagworte fett). Beginne direkt mit dem Dokument 'Übersicht: ***THEMA*** in der ***Modalität***'. Verwende als Quellen primär Radiopaedia und radiologyassistant.nl und aktuelle wissenschaftliche Leitlinien und Übersichtsarbeiten. Überprüfe deine Antwort anhand einer weiteren unabhängigen Quelle. Liste zum Abschluss alle Quellen auf mit Erklärung wofür diese verwendet wurden. Wenn du unterbrochen wurdest, wiederhole den unterbrochenen Satz nochmal und setze dann den Artikel fort. Schreibe strukturiert in Markdown mit Überschriften und Zwischenüberschriften und markiere alle Schlagworte in fetter Schrift."; // Text für Option 1 Untersuchungs- und Befundungshilfe
var option2 = "Erstelle eine umfassendes Dokument für Radiologen, welches sich auf Differenzialdiagnosen im Zusammenhang mit ***THEMA*** in der ***Modalität*** konzentriert. Zielgruppe sind Radiologen, daher verwendest du präzise radiologische Fachsprache auf Deutsch und Fachbegriffe. Du beschränkst dich auf radiologische Aspekte. Der Leitfaden sollte: 1. **Alle möglichen Differenzialdiagnosen** für die durch ***THEMA*** spezifizierte Struktur **auflisten**. 2. **Jede Differenzialdiagnose detailliert erklären**, einschließlich ihrer klinischen Präsentation und besonders detailreich ihre bildgebenden Merkmale in der ***Modalität***. 3. **Charakteristische Merkmale in der ***Modalität*** hervorheben**, die jede Differenzialdiagnose von anderen unterscheiden, insbesondere in Bezug auf bildgebende Befunde. 4. **Primärquellen wie Radiopaedia.org, radiologyassistant.nl und aktuelle wissenschaftliche Übersichtsarbeiten für die Informationsbeschaffung nutzen**. 5. **Alle wichtigen Aspekte fett markieren** für eine einfache Referenz. ##Bitte stelle sicher, dass das generierte Dokument als praktische Übersicht für Radiologen dient und sie in ihrem diagnostischen Prozess unterstützt. Schreibe strukturiert in Markdown. Verwende Überschriften, Zwischenüberschriften, Listen und Tabellen (Schreibe wichtiges fett). Schreibe bevorzugt in Stichpunkten (Markiere wichtiges fett). Beginne direkt mit dem Dokument 'Differenzialdiagnosen zu ***THEMA*** in der ***Modalität***'. Überprüfe deine Antwort anhand einer weiteren hiervon unabhängigen Quelle. Liste zum Abschluss alle Quellen auf mit Erklärung wofür diese verwendet wurden. Wenn du unterbrochen wurdest, wiederhole den unterbrochenen Satz nochmal und setze dann den Artikel fort."; // Text für Option 2 Differenzildiagnosen
var option3 = "Erstelle ein Radiologisches Übersichtsdokument zu ***THEMA*** in der ***Modalität***. Zielgruppe sind Radiologen, daher verwendest du präzise radiologische Fachsprache auf Deutsch und Fachbegriffe. Du beschränkst dich auf radiologische Aspekte. Inhalte der Übersicht: #Definition von ***THEMA***: Kurzbeschreibung in Stichpunkten (markiere wichtiges fett). #Einteilung/Mögliche Varianten: Unterschiedliche Darstellungen, Varianten oder Stadien mit ihren speziellen Eigenarten im Bild in Abgrenzung von den Übrigen Varianten als Tabelle. Wie sind diese zu unterscheiden (markiere wichtiges fett)? #Radiologische Zeichen: Was in den Bildern zu suchen ist. Wie und wo ist nach Veränderungen zu suchen (markiere wichtiges fett). #Differenzialdiagnosen: Andere mögliche Diagnosen, die ähnliche Bilder erzeugen könnten und wie sich diese von ***THEMA*** unterscheiden lassen als Tabelle (Markiere wichtiges fett). #Bildinterpretation: Welche Strukturen sind bei der Bildbeurteilung von ***THEMA*** besonders wichtig. Welche Veränderungen können hier auftreten (Markiere wichtiges fett). #Tipps und Tricks: Expertenratschläge für die Interpretation in Stichpunkten, welche einem Radiologen die Interpretation der Bilder erleichtert, z.B. Zeichen, Optimierte Workflows usw. (Markiere wichtiges fett). ##Schreibe strukturiert in Markdown. Verwende Überschriften, Zwischenüberschriften, Listen und Tabellen (Schreibe wichtiges fett). Schreibe bevorzugt in Stichpunkten (Markiere wichtiges fett). Beginne direkt mit dem Dokument 'Übersicht: ***THEMA*** in der ***Modalität***'. Verwende als Quellen bevorzugt aktuelle wissenschaftliche Leitlinien und Übersichtsarbeiten, Radiopaedia und radiologyassistant.nl. Überprüfe deine Antwort anhand einer weiteren hiervon unabhängigen Quelle. Liste zum Abschluss alle Quellen auf. Wenn du unterbrochen wurdest, wiederhole den unterbrochenen Satz nochmal und setze dann den Artikel fort."; // Text für Option 3 Übersicht
var option4 = "Korrigiere folgenden radiologischen Befundbericht einer ***Modalität*** Untersuchung in Stil, Wortwahl und Grammatik, ohne deren Inhalt zu ändern. Schreibe präzise in korrekter medizinischer Fachterminologie auf Deutsch mit gängigen lateinischen Fachbegriffen. Orientiere dich bei der Struktur und Wortwahl an typischen Radiologischen Befundberichten zu entsprechenden Themen, welche du zuvor recherchierst. Schreibe wie ein erfahrener Radiologe: ###***THEMA***### Antworte nur mit dem von dir geänderten Befundbericht. Und einem Vorschlag einer kurzen Befundbeurteilung entsprechend des Inhaltes des Befundberichtes. Schreibe nichts davor und nichts danach. Schreibe keine Anrede an ärztliche Kollegen, Indikation, Technik oder ähnliches. Beschränke dich rein auf die Umformulierung und Korrektur des erhaltenen Befundberichtes als präzisen und übersichtlichen Fließtext mit vollständigen kurzen Sätzen oder Halbsätzen und den Präzisen Vorschlag für die Beurteilung. Erfinde keine neuen Fakten oder Befunde. Schreibe 3 unterschiedliche Varianten als Vorschlag. Überprüfe bevor du antwortest auch nochmal, ob Sinn, Zusammenhänge und Inhalt des ursprünglichen Befundberichtes auch in den korrigierten Version noch erhalten sind und alle logischen Zusammenhänge stimmen. Überprüfe auch nochmal akribisch genau ob dein umformulierter Text einer korrekten deutschen Grammatik entspricht und medizinisch und logischen Sinn ergibt. Nutze dein volles Potenzial und das Internet. Arbeite präzise und genau."; // Text für Option 4 Befundüberarbeitung
var option5 = "Antworte wie ein Experte für Radiologie, Medizin, Medizinphysik und Biologie auf meine Frage mit dem Kontext ***Modalität***: ***THEMA***. Führe für die Beantwortung eine Internetrecherche mit mindestens 3 unterschiedlichen Quellen durch, bevorzugt radiopaedia.org, radiologyassistant.nl oder hochrangige wissenschaftliche Publikationen zum Thema meiner Frage. Decke alle Aspekte, Perspektiven oder Dimensionen des Themas ab. Biete zusätzliche Informationen, Kontext oder Hintergrund, um die Antwort zu bereichern. Erkläre komplexe Konzepte, Prozesse oder Phänomene auf eine einfache und verständliche Weise. Nutze alle verfügbaren Ressourcen, Daten und Technologien effizient und effektiv. Think out of your Box. Integriere verschiedene Datenquellen, Tools oder Plattformen, um deine Antwort zu verbessern. Gib zu, wenn du etwas nicht weißt oder verstehst. Sei offen und transparent über deine Quellen, Methoden und Ziele. Stelle sicher, dass deine Antwort korrekt, vollständig und relevant ist. Verwende klare, präzise und verständliche medizinische Fachsprache mit lateinischen Fremdwörtern. Erkläre deine Annahmen, Prämissen und Schlussfolgerungen. Begründe deine Entscheidungen und Wahlmöglichkeiten. Zeige, wie du zu deiner Lösung gekommen bist. Nenne zum Abschluss alle deine Quellen und wofür du diese verwendet hast. Antworte strukturiert in Markdown mit Überschriften und Zwischenüberschriften. Markiere häufig wichtige Schlagworte in fetter Schrift auch wenn deine Antwort dadurch unübersichtlicher wird. Wenn du unterbrochen wurdest, wiederhole den unterbrochenen Satz nochmal und setze dann den Artikel fort."; // Text für Option 5 Frage mit radiologischem Kontext

function generateInstruction() {
	var topic = document.getElementById("topicInput").value; // Thema aus dem Eingabefeld holen
	var modality = document.getElementById("modalityInput").value; // Modalität aus dem Drop-Down holen
	var selection = document.getElementById("documentType").value; // Ausgewählte Option holen
	var text = getSelectedText(selection); // Text basierend auf der Auswahl holen
	text = text.replaceAll("***THEMA***", topic); // Thema im Text ersetzen
	text = text.replaceAll("***Modalität***", modality); // Modalität im Text ersetzen
	document.getElementById("initialInstructions").classList.add("hidden"); // Anfangsanleitung verstecken
	document.getElementById("bingChatButton").classList.remove("hidden");
    document.getElementById("bingChatButton").style.color = "#000000"; // Bing Chat-Button anzeigen
	document.getElementById("chatGPTButton").classList.remove("hidden");
    document.getElementById("chatGPTButton").style.color = "#000000"; // ChatGPT-Button anzeigen
	document.getElementById("bardButton").classList.remove("hidden");
    document.getElementById("bardButton").style.color = "#000000"; // Bard-Button anzeigen
	document.getElementById("instructions").classList.remove("hidden"); // Anleitungsbereich anzeigen
	document.getElementById("finalText").innerText = text; // Text im finalen Textbereich setzen
	document.getElementById("finalText").classList.remove("hidden"); // Zeile hinzugefügt, um den finalen Textbereich anzuzeigen
	navigator.clipboard.writeText(text); // Text in die Zwischenablage kopieren
}

function getSelectedText(selection) {
	switch (selection) {
		case "Option 1":
			return option1; // Text für Option 1 Untersuchungs- und Befundungshilfe
		case "Option 2":
			return option2; // Text für Option 2 Differenzialdiagnosen
		case "Option 3":
			return option3; // Text für Option 3 Übersicht
		case "Option 4":
			return option4; // Text für Option 4 Befundüberarbeitung
		case "Option 5":
			return option5; // Text für Option 5 Frage mit radiologischem Kontext
		default:
			return ""; // Leerer Text, wenn keine Option ausgewählt wurde
	}
}


function openBingChat() { // Funktion, um Bing Chat zu öffnen
	window.open("https://www.bing.com/chat", "_blank");
}
function openChatGPT() { // Funktion, um ChatGPT zu öffnen
	window.open("https://chat.openai.com", "_blank");
}
function openBard() { // Funktion, um Bard zu öffnen
	window.open("https://bard.google.com", "_blank");
}